version: '3.7'

services:

  postgres:
    image: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ${PWD}/postgres
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - b0
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    env_file: .env
    networks:
      - b0
    volumes:
      - ${PWD}/src/app/build/:/usr/share/nginx/html:ro

  api:
    image: ${GO_IMAGE}
    env_file: .env
    networks:
      - b0
    ports:
      - 3001:3001
    user: 1000:1000
    volumes:
      - ${PWD}/go:/go
      - ${PWD}/src/api:/api
    working_dir: /api
    command: >
      go run postgres.go

  https-portal:
    image: steveltn/https-portal:1
    networks:
      - b0
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: 'portfolio.local -> http://nginx:80, api.portfolio.local -> http://api:3001'
      STAGE: local
      WEBSOCKET: "true"
    volumes:
      - ${PWD}/https-portal/ssl-certs:/var/lib/https-portal
      - ${PWD}/https-portal/nginx-conf/api.portfolio.local.ssl.conf.erb:/var/lib/nginx-conf/api.portfolio.local.ssl.conf.erb:ro

networks:
  b0:
    name: ${COMPOSE_PROJECT_NAME}-net
